#!/usr/bin/env python
from __future__ import print_function
# -*- coding: latin1 -*-

__author__ = 'Herbert OLiveira Rocha'
FRAMEWORK_VERSION = 'version 1'


# From python
import argparse
import sys
import os
import commands
import re



class DtraceProcess(object):

    def __init__(self):
        self.actualindexfile = 0

    def preprocess_dtrace_file(self, _dtracepath):
        newdtracefile = open("inecp_test.dtrace",'w')

        with open(_dtracepath) as f:
            for line in f:
                txtline = str(line)
                matchskipcontrolpoints = re.search(r'(.*:::.*)', txtline)
                if matchskipcontrolpoints:
                    newdtracefile.write(txtline)
                    #print("<<<<<<<"+txtline, end="")
                else:
                    #newdtracefile.write(txtline+"########")
                    matchreptxt = re.search(r'(.*::.[^:]*)', txtline)
                    if matchreptxt:
                        #print("########"+txtline.replace("::",""), end="")
                        newline = txtline.replace("::","")
                        newdtracefile.write(newline)
                    else:
                        # Handle with return variable generated by ksavir
                        # 1st case in dtrace file
                        matchreturnvar_1 = re.search(r'(variable return)', txtline)
                        # 2st case in dtrace file
                        matchreturnvar_2 = re.search(r'(^return)', txtline)

                        if matchreturnvar_1:
                            newlinereturn = txtline.replace("variable return", "variable \\\\result")
                            newdtracefile.write(newlinereturn)


                        elif matchreturnvar_2:
                            newlinereturn = txtline.replace("return", "\\\\result")
                            newdtracefile.write(newlinereturn)


                        #print("########"+txtline, end="")
                        else:
                            newdtracefile.write(txtline)






        newdtracefile.close()
        os.system("cat inecp_test.dtrace")