#!/usr/bin/env python 
from __future__ import print_function 
import commands 
import sys 
import re 

# Script generated by Inception tool 
# Goal: Check the invariants pointed out in the claims by the ESBMC 

unwindresult = re.compile("unwinding assertion loop") 
violatedresult = re.compile("VERIFICATION FAILED") 
resultesbmc = "" 
# ------------ Checking Claim < 65 > 
unwindstatus = False 
bound = 5 
while not unwindstatus: 
    esbmc_cmd = "esbmc --64 --no-library --claim 65 --unwind " + str(bound) + " /home/hrocha/Documents/Projects_DEV/Inception/test_cases/eacsl_out_c_prog_anot__incep_annot.c" 
    resultesbmc = commands.getoutput(esbmc_cmd) 
    matchunwind = unwindresult.search(resultesbmc) 
    if not matchunwind is not None: 
        unwindstatus = True 
    else: 
        bound += 5 
    
matchresult = violatedresult.search(resultesbmc) 
if matchresult is not None: 
    print(resultesbmc) 
    
    print("===============================================================") 
    print("LINE NUMBER in annotated code < 13 > ") 
    sys.exit() 
else: 
    print("VERIFICATION SUCCESSEFUL") 
    
# ------------ Checking Claim < 1 > 
unwindstatus = False 
bound = 5 
while not unwindstatus: 
    esbmc_cmd = "esbmc --64 --no-library --claim 1 --unwind " + str(bound) + " /home/hrocha/Documents/Projects_DEV/Inception/test_cases/eacsl_out_c_prog_anot__incep_annot.c" 
    resultesbmc = commands.getoutput(esbmc_cmd) 
    matchunwind = unwindresult.search(resultesbmc) 
    if not matchunwind is not None: 
        unwindstatus = True 
    else: 
        bound += 5 
    
matchresult = violatedresult.search(resultesbmc) 
if matchresult is not None: 
    print(resultesbmc) 
    
    print("===============================================================") 
    print("LINE NUMBER in annotated code < 27 > ") 
    sys.exit() 
else: 
    print("VERIFICATION SUCCESSEFUL") 
    
# ------------ Checking Claim < 2 > 
unwindstatus = False 
bound = 5 
while not unwindstatus: 
    esbmc_cmd = "esbmc --64 --no-library --claim 2 --unwind " + str(bound) + " /home/hrocha/Documents/Projects_DEV/Inception/test_cases/eacsl_out_c_prog_anot__incep_annot.c" 
    resultesbmc = commands.getoutput(esbmc_cmd) 
    matchunwind = unwindresult.search(resultesbmc) 
    if not matchunwind is not None: 
        unwindstatus = True 
    else: 
        bound += 5 
    
matchresult = violatedresult.search(resultesbmc) 
if matchresult is not None: 
    print(resultesbmc) 
    
    print("===============================================================") 
    print("LINE NUMBER in annotated code < 27 > ") 
    sys.exit() 
else: 
    print("VERIFICATION SUCCESSEFUL") 
    
# ------------ Checking Claim < 3 > 
unwindstatus = False 
bound = 5 
while not unwindstatus: 
    esbmc_cmd = "esbmc --64 --no-library --claim 3 --unwind " + str(bound) + " /home/hrocha/Documents/Projects_DEV/Inception/test_cases/eacsl_out_c_prog_anot__incep_annot.c" 
    resultesbmc = commands.getoutput(esbmc_cmd) 
    matchunwind = unwindresult.search(resultesbmc) 
    if not matchunwind is not None: 
        unwindstatus = True 
    else: 
        bound += 5 
    
matchresult = violatedresult.search(resultesbmc) 
if matchresult is not None: 
    print(resultesbmc) 
    
    print("===============================================================") 
    print("LINE NUMBER in annotated code < 27 > ") 
    sys.exit() 
else: 
    print("VERIFICATION SUCCESSEFUL") 
    
# ------------ Checking Claim < 6 > 
unwindstatus = False 
bound = 5 
while not unwindstatus: 
    esbmc_cmd = "esbmc --64 --no-library --claim 6 --unwind " + str(bound) + " /home/hrocha/Documents/Projects_DEV/Inception/test_cases/eacsl_out_c_prog_anot__incep_annot.c" 
    resultesbmc = commands.getoutput(esbmc_cmd) 
    matchunwind = unwindresult.search(resultesbmc) 
    if not matchunwind is not None: 
        unwindstatus = True 
    else: 
        bound += 5 
    
matchresult = violatedresult.search(resultesbmc) 
if matchresult is not None: 
    print(resultesbmc) 
    
    print("===============================================================") 
    print("LINE NUMBER in annotated code < 28 > ") 
    sys.exit() 
else: 
    print("VERIFICATION SUCCESSEFUL") 
    
# ------------ Checking Claim < 7 > 
unwindstatus = False 
bound = 5 
while not unwindstatus: 
    esbmc_cmd = "esbmc --64 --no-library --claim 7 --unwind " + str(bound) + " /home/hrocha/Documents/Projects_DEV/Inception/test_cases/eacsl_out_c_prog_anot__incep_annot.c" 
    resultesbmc = commands.getoutput(esbmc_cmd) 
    matchunwind = unwindresult.search(resultesbmc) 
    if not matchunwind is not None: 
        unwindstatus = True 
    else: 
        bound += 5 
    
matchresult = violatedresult.search(resultesbmc) 
if matchresult is not None: 
    print(resultesbmc) 
    
    print("===============================================================") 
    print("LINE NUMBER in annotated code < 29 > ") 
    sys.exit() 
else: 
    print("VERIFICATION SUCCESSEFUL") 
    
# ------------ Checking Claim < 8 > 
unwindstatus = False 
bound = 5 
while not unwindstatus: 
    esbmc_cmd = "esbmc --64 --no-library --claim 8 --unwind " + str(bound) + " /home/hrocha/Documents/Projects_DEV/Inception/test_cases/eacsl_out_c_prog_anot__incep_annot.c" 
    resultesbmc = commands.getoutput(esbmc_cmd) 
    matchunwind = unwindresult.search(resultesbmc) 
    if not matchunwind is not None: 
        unwindstatus = True 
    else: 
        bound += 5 
    
matchresult = violatedresult.search(resultesbmc) 
if matchresult is not None: 
    print(resultesbmc) 
    
    print("===============================================================") 
    print("LINE NUMBER in annotated code < 29 > ") 
    sys.exit() 
else: 
    print("VERIFICATION SUCCESSEFUL") 
    
# ------------ Checking Claim < 9 > 
unwindstatus = False 
bound = 5 
while not unwindstatus: 
    esbmc_cmd = "esbmc --64 --no-library --claim 9 --unwind " + str(bound) + " /home/hrocha/Documents/Projects_DEV/Inception/test_cases/eacsl_out_c_prog_anot__incep_annot.c" 
    resultesbmc = commands.getoutput(esbmc_cmd) 
    matchunwind = unwindresult.search(resultesbmc) 
    if not matchunwind is not None: 
        unwindstatus = True 
    else: 
        bound += 5 
    
matchresult = violatedresult.search(resultesbmc) 
if matchresult is not None: 
    print(resultesbmc) 
    
    print("===============================================================") 
    print("LINE NUMBER in annotated code < 29 > ") 
    sys.exit() 
else: 
    print("VERIFICATION SUCCESSEFUL") 
    
# ------------ Checking Claim < 10 > 
unwindstatus = False 
bound = 5 
while not unwindstatus: 
    esbmc_cmd = "esbmc --64 --no-library --claim 10 --unwind " + str(bound) + " /home/hrocha/Documents/Projects_DEV/Inception/test_cases/eacsl_out_c_prog_anot__incep_annot.c" 
    resultesbmc = commands.getoutput(esbmc_cmd) 
    matchunwind = unwindresult.search(resultesbmc) 
    if not matchunwind is not None: 
        unwindstatus = True 
    else: 
        bound += 5 
    
matchresult = violatedresult.search(resultesbmc) 
if matchresult is not None: 
    print(resultesbmc) 
    
    print("===============================================================") 
    print("LINE NUMBER in annotated code < 29 > ") 
    sys.exit() 
else: 
    print("VERIFICATION SUCCESSEFUL") 
    
# ------------ Checking Claim < 15 > 
unwindstatus = False 
bound = 5 
while not unwindstatus: 
    esbmc_cmd = "esbmc --64 --no-library --claim 15 --unwind " + str(bound) + " /home/hrocha/Documents/Projects_DEV/Inception/test_cases/eacsl_out_c_prog_anot__incep_annot.c" 
    resultesbmc = commands.getoutput(esbmc_cmd) 
    matchunwind = unwindresult.search(resultesbmc) 
    if not matchunwind is not None: 
        unwindstatus = True 
    else: 
        bound += 5 
    
matchresult = violatedresult.search(resultesbmc) 
if matchresult is not None: 
    print(resultesbmc) 
    
    print("===============================================================") 
    print("LINE NUMBER in annotated code < 48 > ") 
    sys.exit() 
else: 
    print("VERIFICATION SUCCESSEFUL") 
    
# ------------ Checking Claim < 16 > 
unwindstatus = False 
bound = 5 
while not unwindstatus: 
    esbmc_cmd = "esbmc --64 --no-library --claim 16 --unwind " + str(bound) + " /home/hrocha/Documents/Projects_DEV/Inception/test_cases/eacsl_out_c_prog_anot__incep_annot.c" 
    resultesbmc = commands.getoutput(esbmc_cmd) 
    matchunwind = unwindresult.search(resultesbmc) 
    if not matchunwind is not None: 
        unwindstatus = True 
    else: 
        bound += 5 
    
matchresult = violatedresult.search(resultesbmc) 
if matchresult is not None: 
    print(resultesbmc) 
    
    print("===============================================================") 
    print("LINE NUMBER in annotated code < 48 > ") 
    sys.exit() 
else: 
    print("VERIFICATION SUCCESSEFUL") 
    
# ------------ Checking Claim < 19 > 
unwindstatus = False 
bound = 5 
while not unwindstatus: 
    esbmc_cmd = "esbmc --64 --no-library --claim 19 --unwind " + str(bound) + " /home/hrocha/Documents/Projects_DEV/Inception/test_cases/eacsl_out_c_prog_anot__incep_annot.c" 
    resultesbmc = commands.getoutput(esbmc_cmd) 
    matchunwind = unwindresult.search(resultesbmc) 
    if not matchunwind is not None: 
        unwindstatus = True 
    else: 
        bound += 5 
    
matchresult = violatedresult.search(resultesbmc) 
if matchresult is not None: 
    print(resultesbmc) 
    
    print("===============================================================") 
    print("LINE NUMBER in annotated code < 39 > ") 
    sys.exit() 
else: 
    print("VERIFICATION SUCCESSEFUL") 
    
# ------------ Checking Claim < 20 > 
unwindstatus = False 
bound = 5 
while not unwindstatus: 
    esbmc_cmd = "esbmc --64 --no-library --claim 20 --unwind " + str(bound) + " /home/hrocha/Documents/Projects_DEV/Inception/test_cases/eacsl_out_c_prog_anot__incep_annot.c" 
    resultesbmc = commands.getoutput(esbmc_cmd) 
    matchunwind = unwindresult.search(resultesbmc) 
    if not matchunwind is not None: 
        unwindstatus = True 
    else: 
        bound += 5 
    
matchresult = violatedresult.search(resultesbmc) 
if matchresult is not None: 
    print(resultesbmc) 
    
    print("===============================================================") 
    print("LINE NUMBER in annotated code < 39 > ") 
    sys.exit() 
else: 
    print("VERIFICATION SUCCESSEFUL") 
    
# ------------ Checking Claim < 21 > 
unwindstatus = False 
bound = 5 
while not unwindstatus: 
    esbmc_cmd = "esbmc --64 --no-library --claim 21 --unwind " + str(bound) + " /home/hrocha/Documents/Projects_DEV/Inception/test_cases/eacsl_out_c_prog_anot__incep_annot.c" 
    resultesbmc = commands.getoutput(esbmc_cmd) 
    matchunwind = unwindresult.search(resultesbmc) 
    if not matchunwind is not None: 
        unwindstatus = True 
    else: 
        bound += 5 
    
matchresult = violatedresult.search(resultesbmc) 
if matchresult is not None: 
    print(resultesbmc) 
    
    print("===============================================================") 
    print("LINE NUMBER in annotated code < 39 > ") 
    sys.exit() 
else: 
    print("VERIFICATION SUCCESSEFUL") 
    
# ------------ Checking Claim < 22 > 
unwindstatus = False 
bound = 5 
while not unwindstatus: 
    esbmc_cmd = "esbmc --64 --no-library --claim 22 --unwind " + str(bound) + " /home/hrocha/Documents/Projects_DEV/Inception/test_cases/eacsl_out_c_prog_anot__incep_annot.c" 
    resultesbmc = commands.getoutput(esbmc_cmd) 
    matchunwind = unwindresult.search(resultesbmc) 
    if not matchunwind is not None: 
        unwindstatus = True 
    else: 
        bound += 5 
    
matchresult = violatedresult.search(resultesbmc) 
if matchresult is not None: 
    print(resultesbmc) 
    
    print("===============================================================") 
    print("LINE NUMBER in annotated code < 39 > ") 
    sys.exit() 
else: 
    print("VERIFICATION SUCCESSEFUL") 
    
# ------------ Checking Claim < 27 > 
unwindstatus = False 
bound = 5 
while not unwindstatus: 
    esbmc_cmd = "esbmc --64 --no-library --claim 27 --unwind " + str(bound) + " /home/hrocha/Documents/Projects_DEV/Inception/test_cases/eacsl_out_c_prog_anot__incep_annot.c" 
    resultesbmc = commands.getoutput(esbmc_cmd) 
    matchunwind = unwindresult.search(resultesbmc) 
    if not matchunwind is not None: 
        unwindstatus = True 
    else: 
        bound += 5 
    
matchresult = violatedresult.search(resultesbmc) 
if matchresult is not None: 
    print(resultesbmc) 
    
    print("===============================================================") 
    print("LINE NUMBER in annotated code < 38 > ") 
    sys.exit() 
else: 
    print("VERIFICATION SUCCESSEFUL") 
    
# ------------ Checking Claim < 28 > 
unwindstatus = False 
bound = 5 
while not unwindstatus: 
    esbmc_cmd = "esbmc --64 --no-library --claim 28 --unwind " + str(bound) + " /home/hrocha/Documents/Projects_DEV/Inception/test_cases/eacsl_out_c_prog_anot__incep_annot.c" 
    resultesbmc = commands.getoutput(esbmc_cmd) 
    matchunwind = unwindresult.search(resultesbmc) 
    if not matchunwind is not None: 
        unwindstatus = True 
    else: 
        bound += 5 
    
matchresult = violatedresult.search(resultesbmc) 
if matchresult is not None: 
    print(resultesbmc) 
    
    print("===============================================================") 
    print("LINE NUMBER in annotated code < 38 > ") 
    sys.exit() 
else: 
    print("VERIFICATION SUCCESSEFUL") 
    
# ------------ Checking Claim < 29 > 
unwindstatus = False 
bound = 5 
while not unwindstatus: 
    esbmc_cmd = "esbmc --64 --no-library --claim 29 --unwind " + str(bound) + " /home/hrocha/Documents/Projects_DEV/Inception/test_cases/eacsl_out_c_prog_anot__incep_annot.c" 
    resultesbmc = commands.getoutput(esbmc_cmd) 
    matchunwind = unwindresult.search(resultesbmc) 
    if not matchunwind is not None: 
        unwindstatus = True 
    else: 
        bound += 5 
    
matchresult = violatedresult.search(resultesbmc) 
if matchresult is not None: 
    print(resultesbmc) 
    
    print("===============================================================") 
    print("LINE NUMBER in annotated code < 38 > ") 
    sys.exit() 
else: 
    print("VERIFICATION SUCCESSEFUL") 
    
# ------------ Checking Claim < 30 > 
unwindstatus = False 
bound = 5 
while not unwindstatus: 
    esbmc_cmd = "esbmc --64 --no-library --claim 30 --unwind " + str(bound) + " /home/hrocha/Documents/Projects_DEV/Inception/test_cases/eacsl_out_c_prog_anot__incep_annot.c" 
    resultesbmc = commands.getoutput(esbmc_cmd) 
    matchunwind = unwindresult.search(resultesbmc) 
    if not matchunwind is not None: 
        unwindstatus = True 
    else: 
        bound += 5 
    
matchresult = violatedresult.search(resultesbmc) 
if matchresult is not None: 
    print(resultesbmc) 
    
    print("===============================================================") 
    print("LINE NUMBER in annotated code < 38 > ") 
    sys.exit() 
else: 
    print("VERIFICATION SUCCESSEFUL") 
    
# ------------ Checking Claim < 37 > 
unwindstatus = False 
bound = 5 
while not unwindstatus: 
    esbmc_cmd = "esbmc --64 --no-library --claim 37 --unwind " + str(bound) + " /home/hrocha/Documents/Projects_DEV/Inception/test_cases/eacsl_out_c_prog_anot__incep_annot.c" 
    resultesbmc = commands.getoutput(esbmc_cmd) 
    matchunwind = unwindresult.search(resultesbmc) 
    if not matchunwind is not None: 
        unwindstatus = True 
    else: 
        bound += 5 
    
matchresult = violatedresult.search(resultesbmc) 
if matchresult is not None: 
    print(resultesbmc) 
    
    print("===============================================================") 
    print("LINE NUMBER in annotated code < 38 > ") 
    sys.exit() 
else: 
    print("VERIFICATION SUCCESSEFUL") 
    
# ------------ Checking Claim < 38 > 
unwindstatus = False 
bound = 5 
while not unwindstatus: 
    esbmc_cmd = "esbmc --64 --no-library --claim 38 --unwind " + str(bound) + " /home/hrocha/Documents/Projects_DEV/Inception/test_cases/eacsl_out_c_prog_anot__incep_annot.c" 
    resultesbmc = commands.getoutput(esbmc_cmd) 
    matchunwind = unwindresult.search(resultesbmc) 
    if not matchunwind is not None: 
        unwindstatus = True 
    else: 
        bound += 5 
    
matchresult = violatedresult.search(resultesbmc) 
if matchresult is not None: 
    print(resultesbmc) 
    
    print("===============================================================") 
    print("LINE NUMBER in annotated code < 38 > ") 
    sys.exit() 
else: 
    print("VERIFICATION SUCCESSEFUL") 
    
# ------------ Checking Claim < 39 > 
unwindstatus = False 
bound = 5 
while not unwindstatus: 
    esbmc_cmd = "esbmc --64 --no-library --claim 39 --unwind " + str(bound) + " /home/hrocha/Documents/Projects_DEV/Inception/test_cases/eacsl_out_c_prog_anot__incep_annot.c" 
    resultesbmc = commands.getoutput(esbmc_cmd) 
    matchunwind = unwindresult.search(resultesbmc) 
    if not matchunwind is not None: 
        unwindstatus = True 
    else: 
        bound += 5 
    
matchresult = violatedresult.search(resultesbmc) 
if matchresult is not None: 
    print(resultesbmc) 
    
    print("===============================================================") 
    print("LINE NUMBER in annotated code < 38 > ") 
    sys.exit() 
else: 
    print("VERIFICATION SUCCESSEFUL") 
    
# ------------ Checking Claim < 40 > 
unwindstatus = False 
bound = 5 
while not unwindstatus: 
    esbmc_cmd = "esbmc --64 --no-library --claim 40 --unwind " + str(bound) + " /home/hrocha/Documents/Projects_DEV/Inception/test_cases/eacsl_out_c_prog_anot__incep_annot.c" 
    resultesbmc = commands.getoutput(esbmc_cmd) 
    matchunwind = unwindresult.search(resultesbmc) 
    if not matchunwind is not None: 
        unwindstatus = True 
    else: 
        bound += 5 
    
matchresult = violatedresult.search(resultesbmc) 
if matchresult is not None: 
    print(resultesbmc) 
    
    print("===============================================================") 
    print("LINE NUMBER in annotated code < 38 > ") 
    sys.exit() 
else: 
    print("VERIFICATION SUCCESSEFUL") 
    
# ------------ Checking Claim < 45 > 
unwindstatus = False 
bound = 5 
while not unwindstatus: 
    esbmc_cmd = "esbmc --64 --no-library --claim 45 --unwind " + str(bound) + " /home/hrocha/Documents/Projects_DEV/Inception/test_cases/eacsl_out_c_prog_anot__incep_annot.c" 
    resultesbmc = commands.getoutput(esbmc_cmd) 
    matchunwind = unwindresult.search(resultesbmc) 
    if not matchunwind is not None: 
        unwindstatus = True 
    else: 
        bound += 5 
    
matchresult = violatedresult.search(resultesbmc) 
if matchresult is not None: 
    print(resultesbmc) 
    
    print("===============================================================") 
    print("LINE NUMBER in annotated code < 39 > ") 
    sys.exit() 
else: 
    print("VERIFICATION SUCCESSEFUL") 
    
# ------------ Checking Claim < 46 > 
unwindstatus = False 
bound = 5 
while not unwindstatus: 
    esbmc_cmd = "esbmc --64 --no-library --claim 46 --unwind " + str(bound) + " /home/hrocha/Documents/Projects_DEV/Inception/test_cases/eacsl_out_c_prog_anot__incep_annot.c" 
    resultesbmc = commands.getoutput(esbmc_cmd) 
    matchunwind = unwindresult.search(resultesbmc) 
    if not matchunwind is not None: 
        unwindstatus = True 
    else: 
        bound += 5 
    
matchresult = violatedresult.search(resultesbmc) 
if matchresult is not None: 
    print(resultesbmc) 
    
    print("===============================================================") 
    print("LINE NUMBER in annotated code < 39 > ") 
    sys.exit() 
else: 
    print("VERIFICATION SUCCESSEFUL") 
    
# ------------ Checking Claim < 47 > 
unwindstatus = False 
bound = 5 
while not unwindstatus: 
    esbmc_cmd = "esbmc --64 --no-library --claim 47 --unwind " + str(bound) + " /home/hrocha/Documents/Projects_DEV/Inception/test_cases/eacsl_out_c_prog_anot__incep_annot.c" 
    resultesbmc = commands.getoutput(esbmc_cmd) 
    matchunwind = unwindresult.search(resultesbmc) 
    if not matchunwind is not None: 
        unwindstatus = True 
    else: 
        bound += 5 
    
matchresult = violatedresult.search(resultesbmc) 
if matchresult is not None: 
    print(resultesbmc) 
    
    print("===============================================================") 
    print("LINE NUMBER in annotated code < 39 > ") 
    sys.exit() 
else: 
    print("VERIFICATION SUCCESSEFUL") 
    
# ------------ Checking Claim < 48 > 
unwindstatus = False 
bound = 5 
while not unwindstatus: 
    esbmc_cmd = "esbmc --64 --no-library --claim 48 --unwind " + str(bound) + " /home/hrocha/Documents/Projects_DEV/Inception/test_cases/eacsl_out_c_prog_anot__incep_annot.c" 
    resultesbmc = commands.getoutput(esbmc_cmd) 
    matchunwind = unwindresult.search(resultesbmc) 
    if not matchunwind is not None: 
        unwindstatus = True 
    else: 
        bound += 5 
    
matchresult = violatedresult.search(resultesbmc) 
if matchresult is not None: 
    print(resultesbmc) 
    
    print("===============================================================") 
    print("LINE NUMBER in annotated code < 39 > ") 
    sys.exit() 
else: 
    print("VERIFICATION SUCCESSEFUL") 
    
# ------------ Checking Claim < 53 > 
unwindstatus = False 
bound = 5 
while not unwindstatus: 
    esbmc_cmd = "esbmc --64 --no-library --claim 53 --unwind " + str(bound) + " /home/hrocha/Documents/Projects_DEV/Inception/test_cases/eacsl_out_c_prog_anot__incep_annot.c" 
    resultesbmc = commands.getoutput(esbmc_cmd) 
    matchunwind = unwindresult.search(resultesbmc) 
    if not matchunwind is not None: 
        unwindstatus = True 
    else: 
        bound += 5 
    
matchresult = violatedresult.search(resultesbmc) 
if matchresult is not None: 
    print(resultesbmc) 
    
    print("===============================================================") 
    print("LINE NUMBER in annotated code < 46 > ") 
    sys.exit() 
else: 
    print("VERIFICATION SUCCESSEFUL") 
    
# ------------ Checking Claim < 54 > 
unwindstatus = False 
bound = 5 
while not unwindstatus: 
    esbmc_cmd = "esbmc --64 --no-library --claim 54 --unwind " + str(bound) + " /home/hrocha/Documents/Projects_DEV/Inception/test_cases/eacsl_out_c_prog_anot__incep_annot.c" 
    resultesbmc = commands.getoutput(esbmc_cmd) 
    matchunwind = unwindresult.search(resultesbmc) 
    if not matchunwind is not None: 
        unwindstatus = True 
    else: 
        bound += 5 
    
matchresult = violatedresult.search(resultesbmc) 
if matchresult is not None: 
    print(resultesbmc) 
    
    print("===============================================================") 
    print("LINE NUMBER in annotated code < 0 > ") 
    sys.exit() 
else: 
    print("VERIFICATION SUCCESSEFUL") 
    
# ------------ Checking Claim < 55 > 
unwindstatus = False 
bound = 5 
while not unwindstatus: 
    esbmc_cmd = "esbmc --64 --no-library --claim 55 --unwind " + str(bound) + " /home/hrocha/Documents/Projects_DEV/Inception/test_cases/eacsl_out_c_prog_anot__incep_annot.c" 
    resultesbmc = commands.getoutput(esbmc_cmd) 
    matchunwind = unwindresult.search(resultesbmc) 
    if not matchunwind is not None: 
        unwindstatus = True 
    else: 
        bound += 5 
    
matchresult = violatedresult.search(resultesbmc) 
if matchresult is not None: 
    print(resultesbmc) 
    
    print("===============================================================") 
    print("LINE NUMBER in annotated code < 0 > ") 
    sys.exit() 
else: 
    print("VERIFICATION SUCCESSEFUL") 
    
# ------------ Checking Claim < 56 > 
unwindstatus = False 
bound = 5 
while not unwindstatus: 
    esbmc_cmd = "esbmc --64 --no-library --claim 56 --unwind " + str(bound) + " /home/hrocha/Documents/Projects_DEV/Inception/test_cases/eacsl_out_c_prog_anot__incep_annot.c" 
    resultesbmc = commands.getoutput(esbmc_cmd) 
    matchunwind = unwindresult.search(resultesbmc) 
    if not matchunwind is not None: 
        unwindstatus = True 
    else: 
        bound += 5 
    
matchresult = violatedresult.search(resultesbmc) 
if matchresult is not None: 
    print(resultesbmc) 
    
    print("===============================================================") 
    print("LINE NUMBER in annotated code < 47 > ") 
    sys.exit() 
else: 
    print("VERIFICATION SUCCESSEFUL") 
    
# ------------ Checking Claim < 59 > 
unwindstatus = False 
bound = 5 
while not unwindstatus: 
    esbmc_cmd = "esbmc --64 --no-library --claim 59 --unwind " + str(bound) + " /home/hrocha/Documents/Projects_DEV/Inception/test_cases/eacsl_out_c_prog_anot__incep_annot.c" 
    resultesbmc = commands.getoutput(esbmc_cmd) 
    matchunwind = unwindresult.search(resultesbmc) 
    if not matchunwind is not None: 
        unwindstatus = True 
    else: 
        bound += 5 
    
matchresult = violatedresult.search(resultesbmc) 
if matchresult is not None: 
    print(resultesbmc) 
    
    print("===============================================================") 
    print("LINE NUMBER in annotated code < 0 > ") 
    sys.exit() 
else: 
    print("VERIFICATION SUCCESSEFUL") 
    
# ------------ Checking Claim < 60 > 
unwindstatus = False 
bound = 5 
while not unwindstatus: 
    esbmc_cmd = "esbmc --64 --no-library --claim 60 --unwind " + str(bound) + " /home/hrocha/Documents/Projects_DEV/Inception/test_cases/eacsl_out_c_prog_anot__incep_annot.c" 
    resultesbmc = commands.getoutput(esbmc_cmd) 
    matchunwind = unwindresult.search(resultesbmc) 
    if not matchunwind is not None: 
        unwindstatus = True 
    else: 
        bound += 5 
    
matchresult = violatedresult.search(resultesbmc) 
if matchresult is not None: 
    print(resultesbmc) 
    
    print("===============================================================") 
    print("LINE NUMBER in annotated code < 0 > ") 
    sys.exit() 
else: 
    print("VERIFICATION SUCCESSEFUL") 
    
# ------------ Checking Claim < 61 > 
unwindstatus = False 
bound = 5 
while not unwindstatus: 
    esbmc_cmd = "esbmc --64 --no-library --claim 61 --unwind " + str(bound) + " /home/hrocha/Documents/Projects_DEV/Inception/test_cases/eacsl_out_c_prog_anot__incep_annot.c" 
    resultesbmc = commands.getoutput(esbmc_cmd) 
    matchunwind = unwindresult.search(resultesbmc) 
    if not matchunwind is not None: 
        unwindstatus = True 
    else: 
        bound += 5 
    
matchresult = violatedresult.search(resultesbmc) 
if matchresult is not None: 
    print(resultesbmc) 
    
    print("===============================================================") 
    print("LINE NUMBER in annotated code < 48 > ") 
    sys.exit() 
else: 
    print("VERIFICATION SUCCESSEFUL") 
    
# ------------ Checking Claim < 64 > 
unwindstatus = False 
bound = 5 
while not unwindstatus: 
    esbmc_cmd = "esbmc --64 --no-library --claim 64 --unwind " + str(bound) + " /home/hrocha/Documents/Projects_DEV/Inception/test_cases/eacsl_out_c_prog_anot__incep_annot.c" 
    resultesbmc = commands.getoutput(esbmc_cmd) 
    matchunwind = unwindresult.search(resultesbmc) 
    if not matchunwind is not None: 
        unwindstatus = True 
    else: 
        bound += 5 
    
matchresult = violatedresult.search(resultesbmc) 
if matchresult is not None: 
    print(resultesbmc) 
    
    print("===============================================================") 
    print("LINE NUMBER in annotated code < 51 > ") 
    sys.exit() 
else: 
    print("VERIFICATION SUCCESSEFUL") 
    
