#!/usr/bin/env python 
from __future__ import print_function 
import commands 
import sys 
import re 

# Script generated by Inception tool 
# Goal: Check the invariants pointed out in the claims by the ESBMC 

unwindresult = re.compile("unwinding assertion loop") 
violatedresult = re.compile("VERIFICATION FAILED") 
resultesbmc = "" 
